volumes:
  pgdata:

services:
  database:
    image: postgres
    container_name: backendpostgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5342:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ../
      dockerfile: ./dockerfiles/prod.dockerfile
    container_name: api-prod
    environment:
      NODE_ENV: production
      DATABASE_URL: 'postgresql://postgres:postgres@backendpostgres:5432/prod'
      PORT: '3000'
    ports:
      - '3000:3000'
    depends_on:
      - database
