volumes:
  devpgdata:

services:
  database:
    image: postgres
    container_name: backendpostgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5342:5432'
    volumes:
      - devpgdata:/var/lib/postgresql/data

  api:
    build:
      context: ../
      dockerfile: ./dockerfiles/dev.dockerfile
    container_name: api-dev
    volumes:
      - ../src:/app/src
    environment:
      NODE_ENV: dev
      DATABASE_URL: 'postgresql://postgres:postgres@backendpostgres:5432/test'
      PORT: '3000'
    ports:
      - '3000:3000'
    depends_on:
      - database
    command: ['npm', 'test']
